
trigger:
- none

pool:
  name: my_agent_pool
parameters:
  - name: env
    type: string
    default: name
stages:
- stage: one_stage
  jobs:
  - job: one_job
    steps:
    - script: echo Hello "${{ parameters.env}}"



   